---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-svc
  namespace: dev-ns
spec:
  type: NodePort
  selector:
    app: nginx-deploy-label
    type: frontend-deploy-label
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
