---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica-set
spec:
  template:
    metadata:
      name: nginx-rs-pod
      labels:
        app: nginx-rs-label
        type: frontend-label
    spec:
      containers:
      - name: nginx-rs-container
        image: nginx
  replicas: 2
  selector:
    matchLabels:
      type: frontend-label
      app: nginx-rs-label


