---
apiVersion: v1
kind: Service
metadata:
  name: nginx-node-svc
spec:
  type: NodePort
  selector:
    app: nginx-rs-label
    type: frontend-label
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
